#!/bin/sh

# Set Gradle options via env.
export GRADLE_OPTS="-Dorg.gradle.caching=false -Dkotlin.incremental=false -Dorg.gradle.logging.stacktrace=all"

./gradlew dependencyGuardBaseline apiDump detektBaseline --continue || exit 1

cd checks/latest || exit 1
./gradlew dependencyGuardBaseline apiDump kotlinUpgradeYarnLock --continue || exit 1

cd ../js-only || exit 1
./gradlew dependencyGuardBaseline apiDump --continue || exit 1

cd ../../
