# Central declaration of dependencies (Gradle Version Catalog)
# https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

# Declaring Rich and/or Ranged Versions
# https://docs.gradle.org/current/userguide/rich_versions.html
# https://docs.gradle.org/current/userguide/single_versions.html


[versions]

fluxoBcvJs = "0.1.0-SNAPSHOT"

# Java/Kotlin compatibility
javaToolchain = "11"
javaLangTarget = "1.8"
kotlinLangVersion = "1.6"

# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin
kotlin = "1.6.0"

pluginPublishVersion = "0.10.1"

# Dokka is a documentation engine for Kotlin/Java
# https://github.com/Kotlin/dokka/releases
# https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin?repo=space-kotlin-dokka-dev
dokka = "1.8.10"

# Public API management tool
# https://github.com/Kotlin/binary-compatibility-validator/releases
# 0.13+ uses Kotlin metadata 0.6.0 (conflicts with AtomicFU!)
bin-compat-validator = "0.12.1"

# https://github.com/detekt/detekt/releases
detekt = "1.23.0-RC3"


[libraries]

kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
plugin-binCompatValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "bin-compat-validator" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

kotlinx-binCompatValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bin-compat-validator" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

# Gradle Versions Plugin: provides a task to determine which dependencies have updates
# https://github.com/ben-manes/gradle-versions-plugin
# https://mvnrepository.com/artifact/com.github.ben-manes/gradle-versions-plugin?repo=gradle-plugins
deps-versions = { id = "com.github.ben-manes.versions", version = "0.46.0" }

# Detect unused and misused dependencies
# https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/tags
# https://mvnrepository.com/artifact/com.autonomousapps/dependency-analysis-gradle-plugin
deps-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.19.0" }

# Plugin that guards against unintentional dependency changes
# https://github.com/dropbox/dependency-guard/releases
deps-guard = { id = "com.dropbox.dependency-guard", version = "0.4.3" }
