# Central declaration of dependencies (Gradle Version Catalog)
# https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

# Declaring Rich and/or Ranged Versions
# https://docs.gradle.org/current/userguide/rich_versions.html
# https://docs.gradle.org/current/userguide/single_versions.html


[versions]

fluxoBcvJs = "0.2.0"

# Public API management tool
# https://github.com/Kotlin/binary-compatibility-validator/releases
# 0.13+ uses Kotlin metadata 0.6.0 (conflicts with AtomicFU!)
bcv = "0.12.1"
bcvMin = "0.8.0"
bcvLatest = "0.13.2"

# Diffutils version, aligned with BCV
# https://github.com/Kotlin/binary-compatibility-validator/blob/0.12.1/build.gradle.kts#L80
diffutils = "1.3.0"

# Java/Kotlin compatibility, aligned with BCV
# https://github.com/Kotlin/binary-compatibility-validator/blob/0.12.1/build.gradle.kts#L99
javaLangTarget = "1.8"
kotlinLangVersion = "1.4"

# Kotlin version, aligned with BCV
# https://github.com/Kotlin/binary-compatibility-validator/blob/0.12.1/gradle.properties#L4
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugin
# https://github.com/JetBrains/kotlin/releases
kotlin = "1.6.0"
kotlinMin = "1.6.20"
kotlinLatest = "1.9.20-Beta"


[libraries]

diffutils = { module = "com.googlecode.java-diff-utils:diffutils", version.ref = "diffutils" }

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-binCompatValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "bcv" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

kotlinx-binCompatValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }

# Publish plugins to the Gradle Plugin Portal
# https://plugins.gradle.org/plugin/com.gradle.plugin-publish
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }

# Plugin that guards against unintentional dependency changes
# https://github.com/dropbox/dependency-guard/releases
deps-guard = { id = "com.dropbox.dependency-guard", version = "0.4.3" }
