
# ProGuard/R8 keep rules
# Auto-generated by Fluxo task :generateShrinkerKeepRulesFromApi
# From API reports (with sha256short):
# - api/plugin.api (0cd0c8e)
# DO NOT EDIT MANUALLY!

-keep,includedescriptorclasses public final class fluxo.bcvjs.FluxoBcvJsPlugin {
    public <init>();
    public synthetic void apply(java.lang.Object);
    public void apply(org.gradle.api.Project);
}

