name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f70248679df316796ffb7123cb0b916bd98cde22
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Prepare release settings
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          RELEASE_PRE=false
          RELEASE_SUFFIX=""
          # Check release type
          if [[ $GITHUB_REF_NAME =~ 'alpha' || $GITHUB_REF_NAME =~ 'beta' || $GITHUB_REF_NAME =~ 'rc' ]]; then
            echo "This is a pre-release!"
            RELEASE_PRE=true
            RELEASE_SUFFIX=" (pre release)"
          fi
          echo "RELEASE_PRE=$RELEASE_PRE" >> $GITHUB_ENV
          echo "RELEASE_SUFFIX=$RELEASE_SUFFIX" >> $GITHUB_ENV

      - name: Release
        # https://github.com/anton-yurchenko/git-release#readme
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          PRE_RELEASE: "${{ env.RELEASE_PRE }}"
          RELEASE_NAME_SUFFIX: "${{ env.RELEASE_SUFFIX }}"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"

# References
# https://github.com/studiometa/vue-mapbox-gl/blob/8c3ca5a/.github/workflows/release.yml#L26
